---
title: "ACS 2016 Tract Level"
author: "Frank Gaunt"
date: "4/19/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
acs2016tract <- read_csv("~/urban-forest/data-raw/R11671742_SL140.csv") %>%
#  select(`FIPS`, `Census Tract`, `Qualifying Name`, `Total Population`:`% Workers 16 Years and Over: Worked At Home`) %>%
  filter(`Households:_7` != "SE_T080_001" & `Total Population` != "NA") 

tidytract2016 <- acs2016tract %>%
  select(FIPS:`Name of Area`, `Census Tract`,`Total Population`:`Area (Land)_1`,
         `Total Population: White Alone`:`Total Population: Two or More Races`, 
         `% Total Population: White Alone`:`% Total Population: Two or More Races`,
         `Population 25 Years and Over: Less than High School`:`% Population 25 Years and Over: Doctorate Degree`, 
         `% Civilian Population in Labor Force 16 Years and Over: Unemployed`, 
         `% Households: Less than $10,000`:`% Households: $200,000 or More`, 
         `Median Household Income (In 2016 Inflation Adjusted Dollars)`, 
         `% Households: No Earnings`, 
         `% Households: with Wage or Salary Income`, `% Households: with Self-Employment Income`, 
         `% Households: with Interest, Dividends, or Net Rental Income`, 
         `% Households: with Social Security Income`, 
         `% Households: with Supplemental Security Income (Ssi)`, 
         `% Households: with Public Assistance Income`, `% Households: with Retirement Income`, 
         `% Households: with Other Types of Income`, 
         `Per Capita Income (In 2016 Inflation Adjusted Dollars)`, `Gini Index`, 
         `% Occupied Housing Units: Owner Occupied`, `Median Gross Rent`, 
         `% Workers 16 Years and Over: Did Not Work At Home: Less than 10 Minutes`:`% Workers 16 Years and Over: Did Not Work At Home: 90 or More Minutes`, 
         `% Workers 16 Years and Over: Worked At Home`) %>%
  rename("Area (Land, in Sq. Miles)" = `Area (Land)_1`)

tidytract2016[, c(1, 3:73)] <- sapply(tidytract2016[, c(1, 3:73)], as.numeric)

tidytract2016 <- tidytract2016 %>%
  mutate(`% Households: Less than $40,000` = `% Households: Less than $10,000` + `% Households: $10,000 to $14,999` + `% Households: $15,000 to $19,999` + `% Households: $20,000 to $24,999` + `% Households: $25,000 to $29,999` + `% Households: $30,000 to $34,999` + `% Households: $35,000 to $39,999`,
         `% Households: $40,000 to $75,000` = `% Households: $40,000 to $44,999` + `% Households: $45,000 to $49,999` + `% Households: $50,000 to $59,999` + `% Households: $60,000 to $74,999`,
         `% Households: $75,000 to $125,000` = `% Households: $75,000 to $99,999` + `% Households: $100,000 to $124,999`,
         `% Households: $125,000 and Over` = `% Households: $125,000 to $149,999` + `% Households: $150,000 to $199,999` + `% Households: $200,000 or More`) 

tidytract2016<-tidytract2016 %>%
  dplyr::select(-36, -36, -37, -38, -39, -40, -41, -42, -43, -44, -45, -46, -47, -48, -49, -50, -51)

tidytract2016 <- tidytract2016 %>%
  mutate(`% Workers with Less than 20 Minute Commute` = `% Workers 16 Years and Over: Did Not Work At Home: Less than 10 Minutes` + `% Workers 16 Years and Over: Did Not Work At Home: 10 to 19 Minutes`,
         `% Workers with 20 to 40 Minute Commute` = `% Workers 16 Years and Over: Did Not Work At Home: 20 to 29 Minutes` + `% Workers 16 Years and Over: Did Not Work At Home: 30 to 39 Minutes`,
         `% Workers with Over 40 Minute Commute` = `% Workers 16 Years and Over: Did Not Work At Home: 40 to 59 Minutes` + `% Workers 16 Years and Over: Did Not Work At Home: 60 to 89 Minutes` + `% Workers 16 Years and Over: Did Not Work At Home: 90 or More Minutes`,
         `% Workers with No Commute` = `% Workers 16 Years and Over: Worked At Home`)

tidytract2016 <- tidytract2016 %>%
  select(-50, -51, -52, -53, -54, -55, -56, -57)

tidytract2016 <- tidytract2016 %>%
  rename("% Population: Less than High School" = `% Population 25 Years and Over: Less than High School`,
         "% Population: High School Graduate" = `% Population 25 Years and Over: High School Graduate (Includes Equivalency)`,
         "% Population: Some College" = `% Population 25 Years and Over: Some College`,
         "% Population: Bachelor's Degree" = `% Population 25 Years and Over: Bachelor's Degree`,
         "% Population: Master's Degree" = `% Population 25 Years and Over: Master's Degree`,
         "% Population: Professional School" = `% Population 25 Years and Over: Professional School Degree`,
         "% Population: Doctorate Degree" = `% Population 25 Years and Over: Doctorate Degree`,
         "Median Family Income" = `Median Household Income (In 2016 Inflation Adjusted Dollars)`,
         "fips" = FIPS,
         "Tract Name" = `Name of Area`,
         "Census Whack" = `Census Tract`)

tidytract2016 <- tidytract2016 %>%
  mutate("Census Tract" = `Census Whack`/100)

tidytract2016$`Census Tract` <- paste0("Census Tract ", tidytract2016$`Census Tract`)

tidytract2016 <- tidytract2016 %>%
  select(fips, `Census Tract`, `Total Population`:`% Workers with No Commute`)

acs2016tractarea <- read_csv("~/urban-forest/data-raw/R11671742_SL140.csv") %>%
  filter(`Households:_7` != "SE_T080_001" & `Total Population` != "NA") %>%
  select(`FIPS`, `Area (Land)`, `Area (Water)`)
acs2016tractarea[,1:3] <- sapply(acs2016tractarea[,1:3], as.numeric)
acs2016tractarea <- acs2016tractarea %>%
  mutate(total_area = `Area (Land)` + `Area (Water)`,
         percent_water = `Area (Water)`/total_area) %>%
  select(FIPS, percent_water)
tidytract2016 <- left_join(tidytract2016, acs2016tractarea, by = c("fips" = "FIPS"))


write_csv(tidytract2016, "~/urban-forest/data/tidytract2016.csv")
```