---
title: "About Files"
author: "Mitzi Zitler, Frank Gaunt, Clark Chang"
date: "5/8/2018"
output: html_document
---

### We Speak For the Trees !


#### Authors
Mitzi Zitler, Frank Gaunt, Clark Chang

#### Themes

Trees! We're looking at the relationship of census data demographics (median family income, percent of workers with no commute, etc) on tree canopy, at the census track level. Each observation is one census tract in the Portland metro area.


#### Relevant Work

Relevant work includes the following literature:

 - "Valuing green infrastructure in Portland, Oregon"
https://www.sciencedirect.com/science/article/pii/S0169204614000036

 - "Trees in the city: valuing street trees in Portland, Oregon"
https://www.fs.usda.gov/treesearch/pubs/36186

 - "The Effect of Trees on Crime in Portland, Oregon"
http://journals.sagepub.com/doi/abs/10.1177/0013916510383238


#### Data


Our census data comes from the American Community Survey's 5 year estimates, 2011 - 2016.
This data was accessed at www.socialexplorer.com Our canopy coverage comes from RLIS, which
is not publically available. We used an aggregated percentage form for our regression, not
the full raster data set. Our street trees data comes from Portland Maps, accessable here:
https://pdx.maps.arcgis.com/home/webmap/viewer.html?webmap=b8c4b91c1afd4057b78eedfbdf2ae231

#### About This App

##### Map Visualization


This visualization is a map of portland from Google Maps, overlaid with a heatmap of the census data from the American Community Survey, overlaid with the street trees data from Portland Maps.

The street trees data is of all the trees on public property - it does not include any trees on private propert. It is mapped with transparency 0.01, so it is just barely visible: this way, the census data by census tract is more visible.


The Tree Sample slider creates random yet reproduceable (seeded) data samples of your choosing.



##### Data Table Output


The data shown in this tab is two numeric demographic variables chosen by the user, and each row in an individual census tract. Those variables are shown in a scatterplot next to the table. To find any individual tract's point, simply click on the row, and the point will enlargen in the scatterplot.



##### Regression Analysis

The regression uses data from the American Community Survey five year estimates for 2011-2016. It was the best model we could find for accounting for spatial autocorrelation while still including a breadth of demographic data. More information is in its white page. 

